baseURL: "https://hannahismael/hugo-website/" 
title: "Hannah Ismael"
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: papers/
          weight: 1 
        - name: Projects
          url: books/
          weight: 2
        - name: CV
          url: /feb2025_cv.pdf
          weight: 3
        - name: Personal Interests
          url: personal/
          weight: 4 
    

params:
    description: "Broadly, I am interested in investigating how law and policy can be built to enable knowledge sharing, access to AI supply chain resources, and transparent model development. I hope to explore where existing frameworks fall short in creating an internet that meaningfully balances considerations such as privacy, transparency, security, and innovation. In the past, this has led me to focus on IP law, privacy regulations, and antitrust law. In light of AI becoming a central priority in many national strategies, I’m particularly interested in how AI policy positions reveal underlying geopolitical concerns."
    author: Hannah Ismael
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    #MainSections: ["publications","projects","CV","personal"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: "Hannah Ismael"
          subtitle: "Broadly, I am interested in investigating how law and policy can be built to enable knowledge sharing, access to AI supply chain resources, and transparent model development. I hope to explore where existing frameworks fall short in creating an internet that meaningfully balances considerations such as privacy, transparency, security, and innovation. In the past, this has led me to focus on IP law, privacy regulations, and antitrust law. In light of AI becoming a central priority in many national strategies, I’m particularly interested in how AI policy positions reveal underlying geopolitical concerns."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: papers/
            - name: Projects
              url: books/
            - name: CV
              url: /hugo-website/feb2025_cv.pdf
            - name: Personal Interests
              url: personal/
        
    socialIcons:
        - name: Linkedin
          url: https://www.linkedin.com/in/hannah-ismael-55bab420b/
        - name: Email
          url: mailto:hannahismael42@berkeley.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=4T2VgpwAAAAJ&hl=en
      

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Hannah Ismael"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
