baseURL: "https://hannahismael/hugo-website/" 
title: Hannah Ismael
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: books/
          weight: 5 
        - name: Projects
          url: papers/
          weight: 2
        - name: CV
          url: courses/
          weight: 3
        - name: Personal Interests
          url: data/
          weight: 4 
        - #name: 
          #url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          #weight: 6

params:
    description: "I am primarily interested in the intersection between public interest issues–privacy, transparency, and security–and market dynamics in AI systems. I enjoy conceptualizing solutions that increase access to AI supply chain resources and center public interest within our AI governance framework. I’m excited to explore antitrust, IP doctrinal, and policy considerations as solutions. "
    author: Hannah Ismael
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Hannah Ismael
          subtitle: "I am primarily interested in the intersection between public interest issues–privacy, transparency, and security–and market dynamics in AI systems. I enjoy conceptualizing solutions that increase access to AI supply chain resources and center public interest within our AI governance framework. I’m excited to explore antitrust, IP doctrinal, and policy considerations as solutions. "
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Data
              url: data/
            - name: Books
              url: books/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:moritz.maria.von.igelfeld@gmail.com
        - name: Zoom
          url: https://www.zoom.us/my/igelfeld
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/pmichaillat
        - name: Substack
          url: https://pmichaillat.substack.com
        - name: YouTube
          url: https://www.youtube.com/@alexandermccallsmithoffici9000
        - name: Twitter
          url: https://twitter.com/McCallSmith

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
